const data = [
  
    {
        "name": "Lavender Co-Ord",
        "description": "Fully Lined,Wrinkle Cotton,Elasticated Waist,Pullover Styling",
        "price": 3300,
        "stock": 0,
        "category": [],
        "image": [
            "https://budandtulips.com/Content/Pro_Images/BTb544ee1.jpg",
            "https://budandtulips.com/Content/Pro_Images/BTb544ee2.jpg",
            "https://budandtulips.com/Content/Pro_Images/BTb544ee3.jpg",
            "https://budandtulips.com/Content/Pro_Images/BTb544ee5.jpg"
        ],
        "size": [],
        "color": [],
        "inbox": "Kurta & Pant",
        "washingInstruction": "Wash inside out,Do not soak or scrub,Hand wash,Dry in shade,Iron on low heat,Do not iron on embellishments",
        "hasOffer": true,
        "offerPrice": 2805,
        "isActive": true,
        "originalPrice": null,
        "originalHasOffer": false
    },
    {
        "name": "Black Makhmal Scalloped Suit",
        "description": "Soft Velvet,Hand Emb Scalloped Sleeves,Hem of Kurta and Pant Bottom,Hand Emb Scattered Sequin on Border of Dupatta,Hand Emb Scattered Sequin on Kurta and Pant",
        "price": 4360,
        "stock": 0,
        "category": [],
        "image": [
            "https://budandtulips.com/Content/Pro_Images/BT4580831.jpg",
            "https://budandtulips.com/Content/Pro_Images/BT4580832.jpg",
            "https://budandtulips.com/Content/Pro_Images/BT4580833.jpg",
            "https://budandtulips.com/Content/Pro_Images/BT4580834.jpg",
            "https://budandtulips.com/Content/Pro_Images/BT4580835.jpg",
            "https://budandtulips.com/Content/Pro_Images/BT4580836.jpg"
        ],
        "size": [],
        "color": [],
        "inbox": "Kurta, dupatta & Pant",
        "washingInstruction": "Dry Clean Only,Steam Iron",
        "hasOffer": true,
        "offerPrice": 3706,
        "isActive": true,
        "originalPrice": null,
        "originalHasOffer": false
    },
    {
        "name": "Hand Embroidered Mangal Suit",
        "description": "Georgette,Hand Emb Flowers Detailing on Neck,Hand Emb Butterflies Detailing on Neck,Hand Emb Flowers Detailing on Yoke,Hand Emb Flowers Detailing on Front of Kurta,Fringes on Hem of Kurta,Fringes On Bottom Of Pant,High Waist Side Slit,Side Pockets in Pant,Fit & Flare Silhouette,Comfort Fit Kurta,Back Elasticated Pant,Yoke Of Kurta Lined,Pant Lined",
        "price": 6739,
        "stock": 0,
        "category": [],
        "image": [
            "https://budandtulips.com/Content/Pro_Images/BT930hz81.jpg",
            "https://budandtulips.com/Content/Pro_Images/BT930hz82.jpg",
            "https://budandtulips.com/Content/Pro_Images/BT930hz83.jpg",
            "https://budandtulips.com/Content/Pro_Images/BT930hz84.jpg",
            "https://budandtulips.com/Content/Pro_Images/BT930hz85.jpg"
        ],
        "size": [],
        "color": [],
        "inbox": "Kurta and Pant",
        "washingInstruction": "Wash Inside Out,Do Not Soak or Scrub,Hand Wash,Dry in Shade,Iron on Low Heat,Do not Iron on Embellishments",
        "hasOffer": true,
        "offerPrice": 5728,
        "isActive": true,
        "originalPrice": null,
        "originalHasOffer": false
    },
    {
        "name": "Lilac Floral Sharara Suit",
        "description": "100% Cotton,Lined Kurta,Lined Sharara,Hand Embroidered Floral Sequins Detailing on Neck Of Kurta,Hand Embroidered Floral Sequins Detailing on Sharara,Hand Tailored Gota Detailing,Straight Fit Silhouette,Comfort Fit Kurta,Fully Elasticated Sharara",
        "price": 3950,
        "stock": 0,
        "category": [],
        "image": [
            "https://budandtulips.com/Content/Pro_Images/BT953hc31.jpg",
            "https://budandtulips.com/Content/Pro_Images/BT953hc32.jpg",
            "https://budandtulips.com/Content/Pro_Images/BT953hc33.jpg",
            "https://budandtulips.com/Content/Pro_Images/BT953hc34.jpg",
            "https://budandtulips.com/Content/Pro_Images/BT953hc35.jpg",
            "https://budandtulips.com/Content/Pro_Images/BT953hc36.jpg"
        ],
        "size": [],
        "color": [],
        "inbox": "Kurta, Dupatta and Sharara",
        "washingInstruction": "Wash Inside Out,Do Not Soak or Scrub,Hand Wash,Dry in Shade,Iron on Low Heat,Do not Iron on Embellishments",
        "hasOffer": true,
        "offerPrice": 2900,
        "isActive": true,
        "originalPrice": null,
        "originalHasOffer": false
    },
    {
        "name": "Hand Embroidered Simone Suit",
        "description": "100% Cotton,Lined Kurta,Hand Done Sequins Detailing on Yoke Of Kurta,Hand Done Beads Detailing on Neck,Hand Done Beads Detailing on Sleeves,Churri Sleeves,Straight Fit Silhouette,Comfort Fit Kurta,Fully Elasticated Pant",
        "price": 4870,
        "stock": 0,
        "category": [],
        "image": [
            "https://budandtulips.com/Content/Pro_Images/BT963hd31.jpg",
            "https://budandtulips.com/Content/Pro_Images/BT963hd32.jpg",
            "https://budandtulips.com/Content/Pro_Images/BT963hd33.jpg",
            "https://budandtulips.com/Content/Pro_Images/BT963hd34.jpg",
            "https://budandtulips.com/Content/Pro_Images/BT963hd35.jpg",
            "https://budandtulips.com/Content/Pro_Images/BT963hd36.jpg"
        ],
        "size": [],
        "color": [],
        "inbox": "Kurta, Dupatta and Pant",
        "washingInstruction": "Wash Inside Out,Do Not Soak or Scrub,Hand Wash,Dry in Shade,Iron on Low Heat,Do not Iron on Embellishments",
        "hasOffer": true,
        "offerPrice": 3600,
        "isActive": true,
        "originalPrice": null,
        "originalHasOffer": false
    },
    {
        "name": "Lilac Classic Suit",
        "description": "Cotton,Sleeve Less Fit And Flare Silhouette,Pleats On Front,Back Elasticated Waist,Front Button Detailing,Boat Neck",
        "price": 2100,
        "stock": 0,
        "category": [],
        "image": [
            "https://budandtulips.com/Content/Pro_Images/BT54hzd31.jpg",
            "https://budandtulips.com/Content/Pro_Images/BT54hzd32.jpg",
            "https://budandtulips.com/Content/Pro_Images/BT54hzd33.jpg",
            "https://budandtulips.com/Content/Pro_Images/BT54hzd34.jpg"
        ],
        "size": [],
        "color": [],
        "inbox": "",
        "washingInstruction": "",
        "hasOffer": true,
        "offerPrice": 1890,
        "isActive": true,
        "originalPrice": null,
        "originalHasOffer": false
    },
    {
        "name": "Hand Embroidered Black Velvet Suit",
        "description": "Soft Velvet,Lined Kurta,Hand Done Sequins Embroidery Detailing on Kurta and Pant,Hand Done Mirror and Beads Embroidery Detailing on Sleeves,Hand Done Mirror and Beads Embroidery Detailing on Pants",
        "price": 6640,
        "stock": 0,
        "category": [],
        "image": [
            "https://budandtulips.com/Content/Pro_Images/BT42hsj31.jpg",
            "https://budandtulips.com/Content/Pro_Images/BT42hsj32.jpg",
            "https://budandtulips.com/Content/Pro_Images/BT42hsj33.jpg",
            "https://budandtulips.com/Content/Pro_Images/BT42hsj34.jpg",
            "https://budandtulips.com/Content/Pro_Images/BT42hsj35.jpg",
            "https://budandtulips.com/Content/Pro_Images/BT42hsj36.jpg",
            "https://budandtulips.com/Content/Pro_Images/BT42hsj37.jpg"
        ],
        "size": [],
        "color": [],
        "inbox": "",
        "washingInstruction": "",
        "hasOffer": true,
        "offerPrice": 5644,
        "isActive": true,
        "originalPrice": null,
        "originalHasOffer": false
    },
    {
        "name": "Lined Cotton Top & Pants",
        "description": "Cotton,Handmade",
        "price": 2475,
        "stock": 0,
        "category": [],
        "image": [
            "https://budandtulips.com/Content/Pro_Images/BT44htw91.jpg",
            "https://budandtulips.com/Content/Pro_Images/BT44htw92.jpg",
            "https://budandtulips.com/Content/Pro_Images/BT44htw93.jpg",
            "https://budandtulips.com/Content/Pro_Images/BT44htw94.jpg",
            "https://budandtulips.com/Content/Pro_Images/BT44htw95.jpg"
        ],
        "size": [],
        "color": [],
        "inbox": "",
        "washingInstruction": "",
        "hasOffer": true,
        "offerPrice": 2250,
        "isActive": true,
        "originalPrice": null,
        "originalHasOffer": false
    },
    {
        "name": "Grey Velvet Shirt With Black Palazzo",
        "description": "Soft Velvet,Front Button Detailing,Elasticated Waist",
        "price": 2895,
        "stock": 0,
        "category": [],
        "image": [
            "https://budandtulips.com/Content/Pro_Images/BT4hqa21.jpg",
            "https://budandtulips.com/Content/Pro_Images/BT4hqa22.jpg",
            "https://budandtulips.com/Content/Pro_Images/BT4hqa23.jpg",
            "https://budandtulips.com/Content/Pro_Images/BT4hqa24.jpg",
            "https://budandtulips.com/Content/Pro_Images/BT4hqa25.jpg"
        ],
        "size": [],
        "color": [],
        "inbox": "",
        "washingInstruction": "",
        "hasOffer": true,
        "offerPrice": 2455,
        "isActive": true,
        "originalPrice": null,
        "originalHasOffer": false
    },
    {
        "name": "Embellished Chiffon Top & Pants",
        "description": "Embellished Chiffon,Full Lined,Hand Embroidery on Top",
        "price": 4750,
        "stock": 0,
        "category": [],
        "image": [
            "https://budandtulips.com/Content/Pro_Images/BT24hfz31.jpg",
            "https://budandtulips.com/Content/Pro_Images/BT24hfz32.jpg",
            "https://budandtulips.com/Content/Pro_Images/BT24hfz33.jpg",
            "https://budandtulips.com/Content/Pro_Images/BT24hfz34.jpg",
            "https://budandtulips.com/Content/Pro_Images/BT24hfz35.jpg"
        ],
        "size": [],
        "color": [],
        "inbox": "",
        "washingInstruction": "",
        "hasOffer": true,
        "offerPrice": 3850,
        "isActive": true,
        "originalPrice": null,
        "originalHasOffer": false
    },
    {
        "name": "Powder Blue Suit",
        "description": "Cotton,Hand Embroidery,Soft,Lightweight",
        "price": 3245,
        "stock": 0,
        "category": [],
        "image": [
            "https://budandtulips.com/Content/Pro_Images/BT4htr21.jpg",
            "https://budandtulips.com/Content/Pro_Images/BT4htr22.jpg",
            "https://budandtulips.com/Content/Pro_Images/BT4htr23.jpg",
            "https://budandtulips.com/Content/Pro_Images/BT4htr24.jpg"
        ],
        "size": [],
        "color": [],
        "inbox": "",
        "washingInstruction": "",
        "hasOffer": true,
        "offerPrice": 3050,
        "isActive": true,
        "originalPrice": null,
        "originalHasOffer": false
    },
    {
        "name": "Black Velvet Dress",
        "description": "Soft Velvet,Hand Done Sequins Detailing,Front Button Detailing,Side Pockets,Loose Fit",
        "price": 3795,
        "stock": 0,
        "category": [],
        "image": [
            "https://budandtulips.com/Content/Pro_Images/BT4hta21.jpg",
            "https://budandtulips.com/Content/Pro_Images/BT4hta22.jpg",
            "https://budandtulips.com/Content/Pro_Images/BT4hta23.jpg",
            "https://budandtulips.com/Content/Pro_Images/BT4hta24.jpg",
            "https://budandtulips.com/Content/Pro_Images/BT4hta25.jpg"
        ],
        "size": [],
        "color": [],
        "inbox": "",
        "washingInstruction": "",
        "hasOffer": true,
        "offerPrice": 3195,
        "isActive": true,
        "originalPrice": null,
        "originalHasOffer": false
    },
    {
        "name": "Grey Velvet Dress",
        "description": "Soft Velvet,Hand Done Sequins Detailing,Front Button Detailing,Side Pockets,Loose Fit",
        "price": 3795,
        "stock": 0,
        "category": [],
        "image": [
            "https://budandtulips.com/Content/Pro_Images/BT4hrz21.jpg",
            "https://budandtulips.com/Content/Pro_Images/BT4hrz22.jpg",
            "https://budandtulips.com/Content/Pro_Images/BT4hrz23.jpg",
            "https://budandtulips.com/Content/Pro_Images/BT4hrz24.jpg",
            "https://budandtulips.com/Content/Pro_Images/BT4hrz25.jpg"
        ],
        "size": [],
        "color": [],
        "inbox": "",
        "washingInstruction": "",
        "hasOffer": true,
        "offerPrice": 3195,
        "isActive": true,
        "originalPrice": null,
        "originalHasOffer": false
    },
    {
        "name": "Hand Embroidered Top",
        "description": "Georgette,Hand Done Embroidery on Top,Full Lined",
        "price": 2245,
        "stock": 0,
        "category": [],
        "image": [
            "https://budandtulips.com/Content/Pro_Images/BT4hzs21.jpg",
            "https://budandtulips.com/Content/Pro_Images/BT4hzs22.jpg",
            "https://budandtulips.com/Content/Pro_Images/BT4hzs23.jpg",
            "https://budandtulips.com/Content/Pro_Images/BT4hzs24.jpg"
        ],
        "size": [],
        "color": [],
        "inbox": "",
        "washingInstruction": "",
        "hasOffer": true,
        "offerPrice": 1995,
        "isActive": true,
        "originalPrice": null,
        "originalHasOffer": false
    },
    {
        "name": "White Floral Cotton Suit",
        "description": "100% Cotton,Lined Kurta,Lined Sharara,Hand Embroidered Floral Sequins Detailing on Neck Of Kurta,Hand Embroidered Floral Sequins Detailing on Sharara,Hand Tailored Gota Detailing,Straight Fit Silhouette,Comfort Fit Kurta,Fully Elasticated Sharara",
        "price": 3950,
        "stock": 0,
        "category": [],
        "image": [
            "https://budandtulips.com/Content/Pro_Images/BT953hc11.jpg",
            "https://budandtulips.com/Content/Pro_Images/BT953hc12.jpg",
            "https://budandtulips.com/Content/Pro_Images/BT953hc13.jpg",
            "https://budandtulips.com/Content/Pro_Images/BT953hc14.jpg",
            "https://budandtulips.com/Content/Pro_Images/BT953hc15.jpg",
            "https://budandtulips.com/Content/Pro_Images/BT953hc16.jpg"
        ],
        "size": [],
        "color": [],
        "inbox": "Kurta, Dupatta and Sharara",
        "washingInstruction": "Wash Inside Out,Do Not Soak or Scrub,Hand Wash,Dry in Shade,Iron on Low Heat,Do not Iron on Embellishments",
        "hasOffer": true,
        "offerPrice": 2900,
        "isActive": true,
        "originalPrice": null,
        "originalHasOffer": false
    }
];

export default data;
